config/routes.rb
Rails.application.routes.draw do
  #homepage
  root "application#home"
  get "/error", to: "application#not_found"

  #signup
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  #login
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  #logout
  post "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :edit, :update] do
    resources :reviews, only: :index
  end

  resources :movies, except: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  resources :lists do
    resources :movies, only: [:add_movie, :delete_movie] do 
      post "add_movie", to: "lists#add_movie", as: "add"
      delete "delete_movie", to: "lists#delete_movie", as: "delete"
    end
  end

  #omniauths
  get "/auth/google_oauth2/callback", to: "sessions#google_omniauth"
  get "/auth/facebook/callback", to: "sessions#facebook_omniauth"
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :lists_movies, dependent: :destroy
  has_many :movies, through: :lists_movies

  validates :title, presence: true

  scope :list_search, -> (term) { joins(:lists_movies).joins(:movies).where("lists.title LIKE :term OR movies.title LIKE :term", term: "%#{term}%").distinct }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :require_login, except: [:index, :show]
    before_action :find_list, except: [:index, :new, :create]
    before_action :not_authorized, only: [:edit, :update, :destroy]

    def index
        if params[:search]
            @lists = List.list_search(params[:search])
            if @lists.blank?
                flash[:message] = "Sorry. There's no such list."
                redirect_to lists_path
            end
        else
            @lists = List.all
        end
    end

    def new
        @list = List.new
    end

    def create
        @list = List.new(list_params)

        if @list.save
            redirect_to list_path(@list)
        else
            render :new
        end
    end

    def show
        if params[:search]
            @movies = Movie.movie_search(params[:search])
            @movies.blank? ? flash[:message] = "'#{params[:search]}' is not found." : flash[:message] = nil
            render :show
        end
    end

    def edit
    end

    def update
        if @list.valid?
            @list.update(list_params)
            redirect_to list_path(@list)
        end
    end

    def destroy
        @list.destroy
        redirect_to user_path(@list.user)
    end

    def add_movie
        @list = List.find_by_id(params[:list_id])
        @movie = Movie.find_by_id(params[:movie_id])
        @list.movies << @movie
        redirect_to list_path(@list)
    end

    def delete_movie
        @list = List.find_by_id(params[:list_id])
        @movie = Movie.find_by_id(params[:movie_id])
        @list.movies.delete(@movie)
        redirect_to list_path(@list)
    end

    private

    def list_params
        params.require(:list).permit(:title, :description).merge(user_id: current_user.id)
    end

    def find_list
        @list = List.find_by_id(params[:id])
    end

    def not_authorized
        if @list.user != current_user
            flash[:error] = "Sorry. You are not authorized to access this page."
            redirect_to list_path(@list)
        end
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<div class="form-group mx-auto mt-2">
  <div class="row mb-3 w-75">
    <div class="col nopadding">
      <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
    </div>
  </div>
  <div class="row mb-3">
    <%= f.text_field :description, placeholder: "Description", class: "form-control" %>
  </div>
</div>

app/views/lists/edit.html.erb
<div class="container my-auto form_container">
  <div class="row">
    <h3 class="page_title">Edit your List</h3>
  </div>
  <div class="container">
    <div class="row">
      <div class="col nopadding">
        <%= render partial: "application/error_messages", locals: { term: @list } %>
      </div>
    </div>
    <%= form_for @list do |f| %>
      <%= render partial: "form", locals: {f: f} %>
      <div class="row">
        <div class="col nopadding">
          <%= f.submit "Save", class: "btn btn-custom" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container-fluid mt-5">
  <div class="container">
    <div class="row mb-3">
      <h1 class="black_page_title">Browse through all lists</h1>
    </div>
    <div class="row mb-4">
      <div class="col-6">
        <%= form_tag lists_path, method: :get do %>
          <div class="input-group">
            <%= search_field_tag :search, nil, placeholder: "Search for a list", class: "form-control" %>
            <%= submit_tag "Search", name: nil, class: "btn movie_list_btn" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="container flash_msg_container">
        <% if flash[:message] %>
          <%= render "application/flash_messages" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row mb-5">
      <div class="row row-cols-1 row-cols-md-2 g-4 mt-0">
        <% @lists.each do |list| %>
          <div class="col">
            <div class="card h-100">
              <div class="card-body">
                <h5 class="card-title"><%= link_to list.title, list_path(list), {class: "custom_link"} %></h5>
                <p class="card-text text-muted"><%= list.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container my-auto form_container">
  <div class="row">
    <h3 class="page_title">Create a New List</h3>
  </div>
  <div class="container">
    <div class="row">
      <div class="col nopadding">
        <%= render partial: "application/error_messages", locals: { term: @list } %>
      </div>
    </div>
    <%= form_for @list do |f| %>
      <%= render partial: "form", locals: { f: f } %>
      <div class="row">
        <div class="col nopadding">
          <%= f.submit "Submit", class: "btn btn-custom" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
  
<div class="container mt-5">
  <% if flash[:error] %>
    <div class="container-fluid">
      <div class="row mb-3">
        <div class="col d-flex justify-content-center">
          <div class="alert alert-danger d-flex align-items-center py-2 " role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            <div>
              <%= flash[:error] %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <h1 class="black_page_title"><%= @list.title %></h1>
  </div>
  <div class="row list_details nopadding">
    <%= @list.description %>
  </div>
  <div class="row list_details mt-3">
    <div class="d-flex flex-row align-items-center">
      <span id="list_creator">Creator:</span>
      <%= link_to "@#{@list.user.username}", user_path(@list.user), class: "custom_link" %>
    </div>
  </div>
  <% if @list.user == current_user %>
    <div class="row mt-2">
      <div class="d-flex flex-row align-items-center">
        <%= link_to "Edit", edit_list_path(@list), {class: "btn list_edit_btn"} %>
        <%= button_to "Delete", list_path(@list), method: :delete, class: "btn list_delete_btn" %>
      </div>
    </div>
    <div class="row mt-4">
      <%= form_tag list_path(@list), method: :get do %>
        <div class="input-group">
          <%= search_field_tag :search, nil, placeholder: "Search for a movie to add to list", id: "movie_list_search", class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn movie_list_btn" %>
        </div>
      <% end %>
    </div>
    <% if params[:search] %>
      <% @movies.each do |movie| %>
        <div class="row mt-3">
          <div class="d-flex flex-row align-items-center">
            <%= movie.title %> (<%= movie.year %>)
            <%= button_to "Add", list_movie_add_path(list_id: @list.id, movie_id: movie.id), class: "btn list_add_btn" %>
          </div>
        </div>
      <% end %>
      <div class="row mt-4">
        <div class="container flash_msg_container">
          <% if flash[:message] %>
            <%= render "application/flash_messages" %>
          <% else %>
          </div>
          <small>If you can't find the movie you're looking for, it's not in our database yet. <%= link_to "Click here to add it!", new_movie_path %></small><br>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>
<div class="container list_container my-5">
  <% if @list.movies.exists? %>
    <div class="table-responsive text-nowrap">
      <table class="table table-hover table-borderless">
        <thead>
          <tr>
            <th scope="col" class="table_header">TITLE</th>
            <th scope="col" class="table_header">YEAR RELEASED</th>
            <th scope="col" class="table_header">GENRE</th>
            <% if @list.user == current_user %>
              <th scope="col"></th>
            <% end %>
          </tr>
        </thead>
        <% @list.movies.each do |movie| %>
          <tbody>
            <tr>
              <td class="align-middle"><%= link_to movie.title, movie_path(movie), class: "custom_link" %></td>
              <td class="align-middle"><%= movie.year %></td>
              <td class="align-middle"><%= movie.genre %></td>
              <% if @list.user == current_user %>
                <td><%= button_to "Delete", list_movie_delete_path(list_id: @list.id, movie_id: movie.id), method: :delete, class: "btn list_delete_btn" %></td>
              <% end %>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  <% end %>
</div>
</div>