config/routes.rb
Rails.application.routes.draw do
  #homepage
  root "application#home"
  get "/error", to: "application#not_found"

  #signup
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  #login
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  #logout
  post "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :edit, :update] do
    resources :reviews, only: :index
  end

  resources :movies, except: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  resources :lists do
    resources :movies, only: [:add_movie, :delete_movie] do 
      post "add_movie", to: "lists#add_movie", as: "add"
      delete "delete_movie", to: "lists#delete_movie", as: "delete"
    end
  end

  #omniauths
  get "/auth/google_oauth2/callback", to: "sessions#google_omniauth"
  get "/auth/facebook/callback", to: "sessions#facebook_omniauth"
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :require_login, except: [:index, :show]
    include MoviesHelper

    def index
        @movie_genres = Movie.distinct_alphabetized_genre

        if params[:genre_name]
            @movies = Movie.filtered_by_genre(params[:genre_name])
        elsif params[:search]
            @movies = Movie.movie_search(params[:search])
            if @movies.blank?
                @newest_movies = Movie.newest_releases
                flash[:message] = "'#{params[:search]}' is not found."
                redirect_to movies_path
            else
                render :index
            end
        else
            @newest_movies = Movie.newest_releases
        end
    end

    def new
        @movie = Movie.new
        @movie_genres = Movie.distinct_alphabetized_genre
    end

    def create
        @movie = Movie.new(movie_params)
        @movie_genres = Movie.distinct_alphabetized_genre

        if @movie.save
            redirect_to movie_path(@movie)
        else
            render :new
        end
    end

    def show
        @movie = Movie.friendly.find(params[:id])
        @reviews = @movie.reviews.top_ten_recently_updated
    end

    private

    def movie_params
        params.require(:movie).permit(:title, :genre, :year)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
    def star_rating(movie)
        if movie.reviews.count == 0
            "n/a"
        else
            if (movie.reviews.sum(:rating)) == 0
                "n/a"
            else
                ((movie.reviews.sum(:rating).to_f)/(movie.reviews.count)).round(2)
            end
        end
    end
end

app/views/movies/_movie_results.html.erb
<div class="row row-cols-1 row-cols-md-3 g-4 mt-0">
<% term.each do |movie| %>
    <div class="col">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title"><%= link_to "#{movie.title} (#{movie.year})", movie_path(movie), {class: "custom_link"} %></h5>
        <p class="card-text"><%= movie.genre %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/index.html.erb
<div class="container-fluid mt-5">
  <div class="container">
    <div class="row mb-4">
      <div class="col d-flex justify-content-center">
        <%= form_tag movies_path, method: :get do %>
          <div class="input-group search_bar">
            <%= search_field_tag :search, nil, placeholder: "Search by title", class: "form-control" %>
            <%= submit_tag "Search", name: nil, class: "btn movie_list_btn" %>
          </div>
        <% end %>
      </div>
      <div class="col d-flex justify-content-center">
        <%= form_with url: movies_path, method: :get do |form| %>
          <div class="input-group">
            <%= form.collection_select :genre_name, @movie_genres, :genre, :genre, {prompt: "Select genre"}, {class: "form-select"} %>
            <%= form.submit "Filter", name: nil, class: "btn movie_list_btn" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="container flash_msg_container">
          <% if flash[:message] %>
            <%= render "application/flash_messages" %>
          <% end %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row mb-5 mt-3">
      <% if params[:genre_name] || params[:search] %>
        <%= render partial: "movie_results", locals: { term: @movies } %>
      <% else %>
        <h2 class="black_page_title">Newest Releases</h2>
        <%= render partial: "movie_results", locals: { term: @newest_movies } %>
      <% end %>
    </div>
    <div class="row mt-3">
      <small>If you can't find the movie you're looking for, it's not in our database yet. <%= link_to "Click here to add it!", new_movie_path, {class: "custom_link"} %></small>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<div class="container my-auto form_container">
  <div class="row">
    <h3 class="page_title">Add a New Movie</h3>
  </div>
  <div class="row mb-3">
    <small>⚠️ You won't be able to edit it later, so make sure all the information is correct! ⚠️</small>
  </div>
  <div class="container">
    <div class="row">
      <div class="col nopadding">
        <%= render partial: "application/error_messages", locals: { term: @movie } %>
      </div>
    </div>
    <%= form_for @movie do |f| %>
      <div class="form-group mx-auto">
        <div class="row mb-3 w-75">
          <div class="col nopadding">
            <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
          <div class="col-4 nopadding">
            <%= f.collection_select :genre, @movie_genres, :genre, :genre, {prompt: "Select genre"}, {class: "form-select text-muted"} %>
          </div>
          <div class="col">
            <div class="row year_field">
              <%= f.text_field :year, placeholder: "Year", class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col nopadding">
            <%= f.submit "Submit", class: "btn btn-custom" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container my-5">
  <div class="row">
    <h1 class="movie_page_title"><%= @movie.title %> (<%= @movie.year %>)</h1>
  </div>
  <div class="row movie_details nopadding">
    Genre: <%= @movie.genre %>
  </div>
  <div class="row movie_details nopadding">
    Overall Rating: ⭐️ <%= star_rating(@movie) %>
  </div>
  <div class="row mt-2">
    <div class="col">
      <%= link_to "Add a Review", new_movie_review_path(@movie), class: "btn btn-custom add_review_font " %>
    </div>
  </div>
  <div class="container">
    <div class="row mt-4 mb-3">
      <h4 class="movie_subtitles nopadding">Featured in these lists</h4>
    </div>
    <ul class="nopadding">
      <div class="row row-cols-1 row-cols-md-3 g-4">
        <% @movie.lists.each do |list| %>
          <div class="col pl-0">
            <div class="card h-100">
              <div class="card-body">
                <h5 class="card-title"><%= link_to list.title, list_path(list), {class: "custom_link"} %></h5>
                <p class="card-text text-muted"><%= list.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </ul>
  </div>
  <div class="container mt-5">
    <div class="row">
      <h4 class="movie_subtitles nopadding mb-3">Reviews</h4>
    </div>
    <%= render "reviews/movie_reviews" %>
  </div>
  <div class="row">
    <%= link_to "Click here to see more reviews", movie_reviews_path(@movie), class: "custom_link more_reviews_link" %>
  </div>
</div>