config/routes.rb
Rails.application.routes.draw do
  #homepage
  root "application#home"
  get "/error", to: "application#not_found"

  #signup
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  #login
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  #logout
  post "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :edit, :update] do
    resources :reviews, only: :index
  end

  resources :movies, except: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  resources :lists do
    resources :movies, only: [:add_movie, :delete_movie] do 
      post "add_movie", to: "lists#add_movie", as: "add"
      delete "delete_movie", to: "lists#delete_movie", as: "delete"
    end
  end

  #omniauths
  get "/auth/google_oauth2/callback", to: "sessions#google_omniauth"
  get "/auth/facebook/callback", to: "sessions#facebook_omniauth"
end

app/models/user.rb
class User < ApplicationRecord    
    has_secure_password

    has_many :lists
    has_many :reviews
    has_many :movies, through: :reviews

    validates :first_name, :last_name, presence: true
    validates :username, presence: true, uniqueness: { message: "is already taken" }, format: { without: /\W/, message: "can only include letters, numbers, and underscores." }
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/ }, presence: true, uniqueness: { message: "is already taken" }

    extend FriendlyId
    friendly_id :username, use: :slugged

    def to_param
        username
    end

    def joined
        created_at.strftime("%-m/%-d/%Y")
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create, :show]
    before_action :find_user, except: [:new, :create]
    before_action :not_authorized, only: [:edit, :update]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
    end 

    def edit
    end

    def update
        if @user.valid?
            if @user.update(user_params)
                redirect_to user_path(@user)
            else
                render :edit
            end
        else
            render :edit
        end
    end

    private
    
    def user_params
        params.require(:user).permit(:first_name, :last_name, :username, :email, :password)
    end

    def find_user
        @user = User.friendly.find_by_username(params[:id])
    end

    def not_authorized
        if @user != current_user
            flash[:error] = "Sorry. You are not authorized to access this page."
            redirect_to user_path(current_user)
        end
    end    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_current_user.html.erb
<div class="container float-start my-5">
  <% if flash[:error] %>
    <div class="container-fluid">
      <div class="row mb-3">
        <div class="col d-flex justify-content-center">
          <div class="alert alert-danger d-flex align-items-center py-2 " role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            <div>
              <%= flash[:error] %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-3 text-end">
      <h3 class="username_font">@<%= @user.username %></h3>
      <h4><%= @user.first_name %> <%= @user.last_name %></h4>
      <span class="joined_date">Joined: <%= @user.joined %></span>
      <ul class="nav flex-column">
        <li class="nav-item mt-2">
          <%= link_to "Edit Profile", edit_user_path(@user), {class: "custom_link"} %>
        </li>
        <li class="nav-item mt-2">
          <%= link_to "Create a New List", new_list_path, {class: "custom_link"} %>
        </li>
        <li class="nav-item mt-2">
          <%= link_to "My Reviews", user_reviews_path(@user), {class: "custom_link"} %>
        </li>
      </ul>
    </div>
    <div class="col-8 mt-4">
      <div class="container">
        <span class="someones_list">My Lists 📝</span>
        <div class="row row-cols-1 row-cols-3 g-4">
          <% @user.lists.each do |list| %>
            <div class="col">
              <div class="card h-100">
                <div class="card-body">
                  <h5 class="card-title"><%= link_to list.title, list_path(list), {class: "custom_link"} %></h5>
                  <p class="card-text"><%= list.description %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_not_logged_in.html.erb
<div class="container float-start my-5">
  <% if flash[:error] %>
    <div class="container-fluid">
      <div class="row mb-3">
        <div class="col d-flex justify-content-center">
          <div class="alert alert-danger d-flex align-items-center py-2 " role="alert">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </svg>
            <div>
              <%= flash[:error] %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-3 text-end">
      <h3 class="username_font">@<%= @user.username %></h3>
      <span class="joined_date">Joined: <%= @user.joined %></span>
      <ul class="nav flex-column">
        <li class="nav-item">
          <%= link_to "#{@user.username}'s Reviews", user_reviews_path(@user), {class: "custom_link"} %>
        </li>
      </ul>
    </div>
    <div class="col-8 mt-4">
      <span class="someones_list"><%= @user.username %>'s Lists 📝</span>
      <div class="row row-cols-1 row-cols-3 g-4">
        <% @user.lists.each do |list| %>
          <div class="col">
            <div class="card h-100">
              <div class="card-body">
                <h5 class="card-title"><%= link_to list.title, list_path(list), {class: "custom_link"} %></h5>
                <p class="card-text"><%= list.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container my-auto" id="edit_profile_container">
  <div class="row mb-3">
    <div class="d-flex justify-content-center">
      <h2 class="page_title">Edit your profile ✍🏻</h2>
    </div>
  </div>
  <%= render partial: "application/error_messages", locals: { term: @user } %>
  <%= form_for @user do |f| %>
    <div class="form-group mx-auto">
      <div class="row">
        <div class="col first_last_name">
          <p><%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %></p>
        </div>
        <div class="col first_last_name">
          <p><%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %></p>
        </div>
      </div>
      <div class="row mt-2">
        <div class="container">
          <div class="input-group">
            <div class="col-1 d-flex justify-content-center">
              <span class="input-group-text">@</span>
            </div>
            <div class="col">
                <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col mt-3 d-flex justify-content-center">
          <p><%= f.submit "Save", class: "btn btn-custom" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container page_padding">
  <div class="row signup_form_padding">
    <div class="col-4">
      <picture>
        <img src="happy_feeling.svg" class="img-fluid" alt="illustration of woman holding balloons">
      </picture>
    </div>
    <div class="col-6">
      <div class="row text-left">
        <ul class="list-inline">
          <li class="list-inline-item h4">Create an account</li>
          <li class="list-inline-item">or <%= link_to "log in", login_path, class: "alt_button custom_link" %></li>
        </ul>
      </div>
      <div class="form-group mx-auto">
        <%= render partial: "application/error_messages", locals: { term: @user } %>
        <%= form_for :user do |f| %>
          <div class="row mb-3">
            <div class="row">
              <div class="col first_last_name">
                <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
              </div>
              <div class="col first_last_name">
                <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="col mt-3">
                <div class="input-group">
                  <span class="input-group-text">@</span>
                  <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col mt-3">
                <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
              </div>
              <div class="col mt-3">
                <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="col mt-3">
                <%= f.submit "Sign Up", class: "btn btn-custom" %>
              </div>
            </div>
          </div>
        <% end %>
        <%= render "application/omniauth" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user == @user %>
    <%= render "current_user" %>
<% else %>
    <%= render "not_logged_in" %>
<% end %>