config/routes.rb
Rails.application.routes.draw do
  #homepage
  root "application#home"
  get "/error", to: "application#not_found"

  #signup
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  #login
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  #logout
  post "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :edit, :update] do
    resources :reviews, only: :index
  end

  resources :movies, except: [:edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :index]
  end

  resources :reviews, only: [:edit, :update, :destroy]

  resources :lists do
    resources :movies, only: [:add_movie, :delete_movie] do 
      post "add_movie", to: "lists#add_movie", as: "add"
      delete "delete_movie", to: "lists#delete_movie", as: "delete"
    end
  end

  #omniauths
  get "/auth/google_oauth2/callback", to: "sessions#google_omniauth"
  get "/auth/facebook/callback", to: "sessions#facebook_omniauth"
end

app/views/layouts/_footer.html.erb
<footer class="mt-auto">
    <div class="container my-2">
    <p class="fs-4" id="footer_name">pilim</p>
    <p id="copyright">&copy; Jenny Kim, 2021</p>
    <small>
        <a href="mailto: kimj1905@gmail.com" target="_blank" class="mx-3 text-muted">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
            </svg>
        </a>
        <a href="https://www.linkedin.com/in/kim-jenny5/" target="_blank" class="mx-3 text-muted">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
            </svg>
        </a>
        <a href="https://github.com/kim-jenny5" target="_blank" class="mx-3 text-muted">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
            </svg>
        </a>
        <a href="https://kim-jenny5.medium.com" target="_blank" class="mx-3 text-muted">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-chat-quote-fill" viewBox="0 0 16 16">
                <path d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM7.194 6.766a1.688 1.688 0 0 0-.227-.272 1.467 1.467 0 0 0-.469-.324l-.008-.004A1.785 1.785 0 0 0 5.734 6C4.776 6 4 6.746 4 7.667c0 .92.776 1.666 1.734 1.666.343 0 .662-.095.931-.26-.137.389-.39.804-.81 1.22a.405.405 0 0 0 .011.59c.173.16.447.155.614-.01 1.334-1.329 1.37-2.758.941-3.706a2.461 2.461 0 0 0-.227-.4zM11 9.073c-.136.389-.39.804-.81 1.22a.405.405 0 0 0 .012.59c.172.16.446.155.613-.01 1.334-1.329 1.37-2.758.942-3.706a2.466 2.466 0 0 0-.228-.4 1.686 1.686 0 0 0-.227-.273 1.466 1.466 0 0 0-.469-.324l-.008-.004A1.785 1.785 0 0 0 10.07 6c-.957 0-1.734.746-1.734 1.667 0 .92.777 1.666 1.734 1.666.343 0 .662-.095.931-.26z"/>
            </svg>
        </a>
    </small>
    </div>
</footer>

app/views/layouts/_home.html.erb
<a class="navbar-brand" href="<%= root_path %>">
    <img src="film.jpg" width="35" height="35" class="d-inline-block align-top" alt="">
    <span class="fs-4 app_name">pilim</span>
</a>
<div class="navbar-nav navbar-right">
    <a class="nav-item nav-link mx-3" id="login_link" href="<%= login_path %>">Log In</a>
    <a class="nav-item nav-link mx-3" id="signup_link" href="<%= signup_path %>">Sign Up</a>
</div>

app/views/layouts/_logged_in.html.erb
<a class="navbar-brand" href="<%= user_path(current_user) %>">
    <span class="fs-3 no_picture_logo app_name">pilim</span>
</a>
<div class="collapse navbar-collapse">
    <div class="navbar-nav">
        <a class="nav-link" href="<%= lists_path %>">All Lists</a>
        <a class="nav-link" href="<%= movies_path %>">All Movies</a>
    </div>
</div>
<div class="navbar-nav navbar-right">
    <%= button_to "Log Out", logout_path, {class: "logout_button"} %>
</div>

app/views/layouts/_logged_in_navbar.html.erb
<a href="<%= user_path(current_user) %>">pilim</a>
<a href="<%= lists_path %>">All Lists</a>
<a href="<%= movies_path %>">All Movies</a>
<%= button_to "Log Out", logout_path %>

app/views/layouts/_login_signup.html.erb
<a class="navbar-brand mx-auto" href="<%= root_path %>">
    <img src="film.jpg" width="35" height="35" class="d-inline-block align-top" alt="">
    <span class="fs-4 app_name">pilim</span>
</a>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-custom">
    <div class="container-fluid">
        <% if logged_in? %>
            <%= render "layouts/logged_in" %>
        <% elsif current_page?(signup_path) || current_page?(login_path) %>
            <%= render "layouts/login_signup" %>
        <% elsif current_page?(root_path) %>
            <%= render "layouts/home" %>
        <% else %>
            <%= render "layouts/no_user" %>
        <% end %>
    </div>
</nav>

app/views/layouts/_no_user.html.erb
<a class="navbar-brand" href="<%= root_path %>">
    <span class="fs-3 no_picture_logo app_name">pilim</span>
</a>
<div class="collapse navbar-collapse">
    <div class="navbar-nav">
        <a class="nav-link" href="<%= lists_path %>">All Lists</a>
        <a class="nav-link" href="<%= movies_path %>">All Movies</a>
    </div>
</div>
<div class="navbar-nav navbar-right">
    <a class="nav-item nav-link mx-3" id="login_link" href="<%= login_path %>">Log In</a>
    <a class="nav-item nav-link mx-3" id="signup_link" href="<%= signup_path %>">Sign Up</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pilim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render "layouts/navbar" %>

    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/home_navbar.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pilim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href="<%= root_path %>">pilim</a>
    <a href="<%= login_path %>">Log In</a>
    <a href="<%= signup_path %>">Sign Up</a>

    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/no_user_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pilim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href="<%= root_path %>">pilim</a>
    <a href="<%= lists_path %>">All Lists</a>
    <a href="<%= movies_path %>">All Movies</a>
    <a href="<%= login_path %>">Log In</a>
    <a href="<%= signup_path %>">Sign Up</a>

    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>